# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YudNqmDCRk4HWD_zn0rKhhq_tKYQjIZc
"""

path = 'countslopesdiff.txt'
with open(path, 'r') as f:
  lines = f.readlines()
countslopes = []
for line in lines:
  try:
    countslopes.append(eval(line))
  except:
    continue

def countnegatives(entry):
  count = 0
  for item in entry:
    if item < 0:
      count += 1
  return count
count = 0
for entry in countslopes:
  count += countnegatives(entry)

print(count)
print(3*len(countslopes))
print(count/(3*len(countslopes)) * 100)

countslopes60 = []
countslopes120 = []
for entry in countslopes[::2]:
  countslopes60.append(entry)

for entry in countslopes[1::2]:
  countslopes120.append(entry)

count60 = 0
for entry in countslopes60:
  count60 += countnegatives(entry) 

print(count60/(3*len(countslopes60)) * 100)

path = 'metricslopesdiff.txt'
with open(path, 'r') as f:
  lines = f.readlines()
metricslopes = []
for line in lines:
  try:
    metricslopes.append(eval(line))
  except:
    continue

count = 0
for entry in metricslopes:
  count += countnegatives(entry)

print(count/(9*len(metricslopes)) * 100)

metricslopes60 = []
metricslopes120 = []
for entry in metricslopes[::2]:
  metricslopes60.append(entry)

for entry in countslopes[1::2]:
  metricslopes120.append(entry)

count60 = 0
for entry in metricslopes60:
  count60 += countnegatives(entry) 
print(count60/(9*len(metricslopes60)) * 100)

frepos = 0
sipos = 0
fkgpos = 0
clipos = 0
aripos = 0
dcrspos = 0
dwpos = 0
lwfpos = 0
gfpos = 0

for ms in metricslopes:
  if ms[0] > 0:
    frepos += 1
  if ms[1] > 0:
    sipos += 1
  if ms[2] > 0:
    fkgpos += 1
  if ms[3] > 0:
    clipos += 1
  if ms[4] > 0:
    aripos += 1
  if ms[5] > 0:
    dcrspos += 1
  if ms[6] > 0:
    dwpos += 1
  if ms[7] > 0:
    lwfpos += 1
  if ms[8] > 0:
    gfpos += 1

print('=====================')
print('FRE positive % = ', round((frepos/len(metricslopes)) * 100, 2))
print('SI positive % = ', round((sipos/len(metricslopes)) * 100, 2))
print('FKG positive % = ', round((fkgpos/len(metricslopes)) * 100, 2))
print('CLI positive % = ', round((clipos/len(metricslopes)) * 100, 2))
print('ARI positive % = ', round((aripos/len(metricslopes)) * 100, 2))
print('DCRS positive % = ', round((dcrspos/len(metricslopes)) * 100, 2))
print('DW positive % = ', round((dwpos/len(metricslopes)) * 100, 2))
print('LWF positive % = ', round((lwfpos/len(metricslopes)) * 100, 2))
print('GF positive % = ', round((gfpos/len(metricslopes)) * 100, 2))
